/**
 * AI Dashboard Type Definitions
 * 
 * This module extends existing AI types from the server to create minimal,
 * dashboard-specific types that maximize reuse and prevent type drift.
 * 
 * Key Design Principles:
 * - Extend existing server AI types rather than duplicating
 * - Minimal new types only when dashboard-specific features are needed
 * - CEFR level integration for French language learning
 * - Type safety for polling and job management
 * 
 * @author AI Development Team
 * @since 2025-08-22
 */

// Note: Import paths use .js extensions for ESM compliance
// These types will be available once server types are properly exposed to client

/**
 * CEFR (Common European Framework of Reference) levels for French language proficiency
 * Used throughout the dashboard for personalized content difficulty
 */
export type CEFRLevel = 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';

/**
 * Daily Learning Plan generated by AI based on user progress and preferences
 * Integrates with existing content generation and assessment systems
 */
export interface DailyLearningPlan {
  /** Unique identifier for the learning plan */
  id: string;
  /** User ID this plan was generated for */
  userId: string;
  /** ISO timestamp when plan was generated */
  generatedAt: string;
  /** Array of AI-generated lessons for the day */
  lessons: any[]; // TODO: Replace with proper lesson type from server when available
  /** Personalized content recommendations */
  recommendations: ContentRecommendation[];
  /** Estimated total duration in minutes */
  estimatedDuration: number;
  /** Target CEFR difficulty level */
  difficulty: CEFRLevel;
  /** Optional metadata for analytics */
  metadata?: {
    /** User's current streak */
    streakDays?: number;
    /** Focus areas identified by AI */
    focusAreas?: string[];
    /** Confidence score for plan quality */
    confidenceScore?: number;
  };
}

/**
 * AI-generated content recommendation with reasoning and prioritization
 * Used for personalized learning suggestions
 */
export interface ContentRecommendation {
  /** Unique identifier for the recommendation */
  id: string;
  /** Human-readable title */
  title: string;
  /** Detailed description of the content */
  description: string;
  /** Type of learning content */
  type: 'lesson' | 'vocabulary_drill' | 'grammar_exercise' | 'conversation_practice';
  /** CEFR difficulty level */
  difficulty: CEFRLevel;
  /** Estimated completion time in minutes */
  estimatedTime: number;
  /** AI reasoning for why this is recommended */
  reason: string;
  /** Priority level for presentation ordering */
  priority: 'high' | 'medium' | 'low';
  /** Optional tags for categorization */
  tags?: string[];
  /** Confidence score from AI recommendation engine */
  confidenceScore?: number;
}

/**
 * AI content generation job status tracking
 * Used for real-time polling and progress updates
 */
export interface AIGenerationJob {
  /** Unique job identifier */
  jobId: string;
  /** Current job status */
  status: 'pending' | 'processing' | 'completed' | 'failed' | 'cancelled';
  /** Progress percentage (0-100) */
  progress?: number;
  /** Generated content result when completed */
  result?: any; // TODO: Type this based on content type when server types are available
  /** Error message if job failed */
  error?: string;
  /** ISO timestamp when job was created */
  createdAt: string;
  /** ISO timestamp when job was last updated */
  updatedAt: string;
  /** Job type for better progress tracking */
  jobType?: 'lesson' | 'vocabulary' | 'grammar' | 'assessment';
  /** Estimated completion time in seconds */
  estimatedDuration?: number;
}

/**
 * Content generation request payload
 * Used to initiate AI content creation
 */
export interface ContentGenerationRequest {
  /** Topic or subject for content generation */
  topic: string;
  /** Type of content to generate */
  contentType: 'lesson' | 'vocabulary_drill' | 'grammar_exercise' | 'conversation_practice';
  /** Target CEFR difficulty level */
  difficulty?: CEFRLevel;
  /** Desired completion time in minutes */
  estimatedTime?: number;
  /** Specific areas to focus on */
  focusAreas?: string[];
  /** Additional context for AI generation */
  context?: {
    /** User's current progress level */
    userLevel?: CEFRLevel;
    /** Previous lesson topics for continuity */
    previousTopics?: string[];
    /** User's weak areas for targeted practice */
    weaknessAreas?: string[];
  };
}

/**
 * Dashboard state management interface
 * Used with useReducer for optimized state management
 */
export interface AIDashboardState {
  /** Current daily learning plan */
  dailyPlan: DailyLearningPlan | null;
  /** Array of personalized recommendations */
  recommendations: ContentRecommendation[];
  /** Active content generation jobs */
  activeJobs: Map<string, AIGenerationJob>;
  /** Global loading state */
  isLoading: boolean;
  /** Current error message if any */
  error: string | null;
  /** ISO timestamp of last successful update */
  lastUpdated: string | null;
  /** Cache for performance optimization */
  cache?: {
    /** Cached daily plans by date */
    dailyPlans?: Map<string, DailyLearningPlan>;
    /** Cached recommendations with TTL */
    recommendations?: Map<string, { data: ContentRecommendation[]; expires: number }>;
  };
}

/**
 * Dashboard action types for useReducer pattern
 * Provides type-safe state management
 */
export type AIDashboardAction =
  | { type: 'SET_LOADING'; payload: boolean }
  | { type: 'SET_ERROR'; payload: string | null }
  | { type: 'SET_DAILY_PLAN'; payload: DailyLearningPlan }
  | { type: 'SET_RECOMMENDATIONS'; payload: ContentRecommendation[] }
  | { type: 'ADD_JOB'; payload: AIGenerationJob }
  | { type: 'UPDATE_JOB'; payload: { jobId: string; job: AIGenerationJob } }
  | { type: 'REMOVE_JOB'; payload: string }
  | { type: 'SET_LAST_UPDATED'; payload: string }
  | { type: 'CLEAR_CACHE'; payload?: string } // Optional cache key to clear specific cache
  | { type: 'UPDATE_CACHE'; payload: { key: string; data: any; ttl?: number } };

/**
 * Polling configuration options
 * Used to customize polling behavior for different job types
 */
export interface PollingOptions {
  /** Initial polling interval in milliseconds */
  initialInterval?: number;
  /** Maximum polling interval in milliseconds */
  maxInterval?: number;
  /** Maximum number of polling attempts */
  maxRetries?: number;
  /** Backoff multiplier for exponential backoff */
  backoffMultiplier?: number;
  /** Job type for adaptive polling intervals */
  jobType?: 'lesson' | 'vocabulary' | 'grammar' | 'assessment';
  /** Custom timeout for specific job types */
  timeout?: number;
}

/**
 * Polling manager status information
 * Used for debugging and monitoring
 */
export interface PollingManagerStatus {
  /** Number of active polling operations */
  activePolls: number;
  /** Maximum concurrent polling limit */
  maxConcurrent: number;
  /** Number of operations waiting in queue */
  waitingQueue: number;
  /** Total operations processed since initialization */
  totalProcessed?: number;
  /** Average polling success rate */
  successRate?: number;
}

/**
 * Content generation job with enhanced metadata
 * Extended version for detailed tracking
 */
export interface EnhancedAIGenerationJob extends AIGenerationJob {
  /** User who initiated the job */
  userId: string;
  /** Job priority level */
  priority: 'low' | 'normal' | 'high';
  /** Retry count for failed jobs */
  retryCount?: number;
  /** Maximum retry attempts */
  maxRetries?: number;
  /** Queue position for pending jobs */
  queuePosition?: number;
  /** Resource usage metrics */
  metrics?: {
    /** Processing time in milliseconds */
    processingTime?: number;
    /** AI tokens consumed */
    tokensUsed?: number;
    /** Memory usage in MB */
    memoryUsage?: number;
  };
}

/**
 * API response wrapper for consistent error handling
 * Used to standardize all AI dashboard API responses
 */
export interface APIResponse<T = any> {
  /** Indicates if the operation was successful */
  success: boolean;
  /** Response data when successful */
  data?: T;
  /** Error message when unsuccessful */
  error?: string;
  /** Additional metadata */
  metadata?: {
    /** Request timestamp */
    timestamp: string;
    /** Request ID for tracking */
    requestId?: string;
    /** Cache status */
    cached?: boolean;
    /** Processing time in milliseconds */
    processingTime?: number;
  };
}

/**
 * Batch job processing request
 * Used for efficient processing of multiple content generation requests
 */
export interface BatchContentRequest {
  /** Array of content generation requests */
  requests: ContentGenerationRequest[];
  /** Batch processing options */
  options?: {
    /** Maximum concurrent jobs */
    maxConcurrent?: number;
    /** Batch priority level */
    priority?: 'low' | 'normal' | 'high';
    /** Callback URL for batch completion notification */
    callbackUrl?: string;
  };
}

/**
 * Dashboard analytics data structure
 * Used for tracking user engagement and AI performance
 */
export interface DashboardAnalytics {
  /** User engagement metrics */
  engagement: {
    /** Daily active sessions */
    dailySessions: number;
    /** Average session duration in minutes */
    avgSessionDuration: number;
    /** Content completion rate */
    completionRate: number;
  };
  /** AI performance metrics */
  aiPerformance: {
    /** Average content generation time */
    avgGenerationTime: number;
    /** User satisfaction score (1-5) */
    satisfactionScore: number;
    /** Content acceptance rate */
    contentAcceptanceRate: number;
  };
  /** Learning progress metrics */
  learningProgress: {
    /** Current CEFR level */
    currentLevel: CEFRLevel;
    /** Skills improvement rate */
    improvementRate: number;
    /** Streak days */
    streakDays: number;
  };
}
