rules:
  - id: knex-select
    languages:
      - javascript
      - typescript
    pattern: knex(...).select(...)
    message: "Knex SELECT query detected"
    severity: INFO

  - id: missing-validation
    languages:
      - javascript
      - typescript
    pattern: req.body && !validate(req.body)
    message: "Potentially unvalidated request body"
    severity: WARNING
