/**
 * Model functions for interacting with the `userFriendships` table.
 * 
 * @description Provides comprehensive CRUD operations and relationship queries
 * for the social friends feature, following established User.ts patterns exactly.
 * 
 * @author Social Features Implementation Team
 * @since 2025-09-22
 * @version 1.0.0
 * 
 * @performance_optimizations
 * - Leverages database indexes for efficient friendship queries
 * - Bidirectional relationship queries with single database calls
 * - Proper transaction support for race condition prevention
 * - Optimized status-based filtering using database indexes
 * 
 * @design_patterns
 * - Follows exact User.ts model structure and conventions
 * - Objection.js Model class integration for ORM capabilities
 * - Schema/ApplicationData separation for clean data transformation
 * - Comprehensive TypeScript typing with proper null handling
 */

import { Model } from 'objection';
import db from '../config/db.js';
import { User } from './User.js';

/**
 * Objection.js Model class for UserFriendship table ORM capabilities
 * 
 * @class UserFriendship
 * @extends {Model}
 * 
 * @description Provides ORM functionality for userFriendships table,
 * enabling advanced query capabilities and relationship mapping.
 */
export class UserFriendship extends Model {
  static tableName = 'userFriendships';

  id!: number;
  userId!: number;
  friendId!: number;
  status!: 'pending' | 'accepted' | 'blocked';
  createdAt!: string;
  updatedAt!: string;

  // Virtual properties for related data
  requester?: any;
  friend?: any;

  static get relationMappings() {
    return {
      requester: {
        relation: Model.BelongsToOneRelation,
        modelClass: User,
        join: {
          from: 'userFriendships.userId',
          to: 'users.id'
        }
      },
      friend: {
        relation: Model.BelongsToOneRelation,
        modelClass: User,
        join: {
          from: 'userFriendships.friendId',
          to: 'users.id'
        }
      }
    };
  }
}

/**
 * Interface representing the UserFriendship table structure
 * 
 * @interface UserFriendshipSchema
 * 
 * @description Raw database schema interface matching the userFriendships table
 * structure exactly. Used for internal database operations and type safety.
 * 
 * @property {number} [id] - Auto-increment primary key (optional for inserts)
 * @property {number} userId - Foreign key to users.id (friendship initiator)
 * @property {number} friendId - Foreign key to users.id (friendship target)  
 * @property {'pending' | 'accepted' | 'blocked'} status - Current friendship status
 * @property {string} [createdAt] - Timestamp when friendship was created
 * @property {string} [updatedAt] - Timestamp when friendship was last updated
 */
export interface UserFriendshipSchema {
  id?: number;
  userId: number;
  friendId: number;
  status: 'pending' | 'accepted' | 'blocked';
  createdAt?: string;
  updatedAt?: string;
}

/**
 * Type for creating a new friendship, omitting fields generated by the database
 * 
 * @type NewUserFriendship
 * 
 * @description Used for friendship creation operations, excluding auto-generated
 * fields like id, createdAt, and updatedAt which are handled by the database.
 * Status defaults to 'pending' if not specified.
 * 
 * @example
 * ```typescript
 * const newFriendship: NewUserFriendship = {
 *   userId: 1,
 *   friendId: 2,
 *   status: 'pending' // optional, defaults to 'pending'
 * };
 * ```
 */
export type NewUserFriendship = Omit<UserFriendshipSchema, 'id' | 'createdAt' | 'updatedAt'> & {
  status?: 'pending' | 'accepted' | 'blocked'; // Optional with default
};

/**
 * Type for friendship data returned to application with enhanced information
 * 
 * @interface UserFriendshipApplicationData
 * 
 * @description Application-facing interface that includes user information
 * for better frontend integration. Provides complete friendship context
 * including friend's basic profile information.
 * 
 * @property {number} id - Friendship record primary key
 * @property {number} userId - Friendship initiator user ID
 * @property {number} friendId - Target friend user ID
 * @property {'pending' | 'accepted' | 'blocked'} status - Current friendship status
 * @property {string} createdAt - When friendship request was created
 * @property {string} updatedAt - When friendship status was last updated
 * @property {object} [friendInfo] - Basic friend profile information (when available)
 * @property {string} [friendInfo.email] - Friend's email address
 * @property {string} [friendInfo.firstName] - Friend's first name
 * @property {string} [friendInfo.lastName] - Friend's last name
 */
export interface UserFriendshipApplicationData {
  id: number;
  userId: number;
  friendId: number;
  status: 'pending' | 'accepted' | 'blocked';
  createdAt: string;
  updatedAt: string;
  friendInfo?: {
    email: string;
    firstName?: string | null;
    lastName?: string | null;
  };
}

/**
 * Helper to convert DB schema to application data format
 * 
 * @function mapUserFriendshipToApplicationData
 * @param {UserFriendshipSchema} friendship - Raw database friendship record
 * @param {object} [friendInfo] - Optional friend profile information
 * @returns {UserFriendshipApplicationData} Formatted application data
 * 
 * @description Transforms raw database friendship records into application-friendly
 * format with proper type safety and optional friend information enrichment.
 * Follows exact patterns from User.ts mapUserToApplicationData function.
 * 
 * @example
 * ```typescript
 * const dbFriendship = { id: 1, userId: 1, friendId: 2, status: 'accepted', ... };
 * const appData = mapUserFriendshipToApplicationData(dbFriendship);
 * ```
 */
function mapUserFriendshipToApplicationData(
  friendship: UserFriendshipSchema,
  friendInfo?: { email: string; firstName?: string | null; lastName?: string | null }
): UserFriendshipApplicationData {
  return {
    id: friendship.id!,
    userId: friendship.userId,
    friendId: friendship.friendId,
    status: friendship.status,
    createdAt: friendship.createdAt!,
    updatedAt: friendship.updatedAt!,
    friendInfo,
  };
}

/**
 * Creates a new friendship request between two users
 * 
 * @function createFriendship
 * @param {NewUserFriendship} friendshipData - Friendship data for creation
 * @returns {Promise<UserFriendshipApplicationData>} Created friendship record
 * 
 * @throws {Error} If friendship already exists or users don't exist
 * @throws {Error} If user tries to befriend themselves
 * 
 * @description Creates a new friendship request with proper validation and
 * database constraints. Uses database-level unique constraints to prevent
 * duplicate friendship requests between the same users.
 * 
 * @performance Uses single INSERT with RETURNING for atomic operation
 * 
 * @example
 * ```typescript
 * const friendship = await createFriendship({
 *   userId: 1,
 *   friendId: 2,
 *   status: 'pending'
 * });
 * ```
 */
export const createFriendship = async (friendshipData: NewUserFriendship): Promise<UserFriendshipApplicationData> => {
  // Prepare data for insertion with default status
  const friendshipToInsert: Partial<UserFriendshipSchema> = {
    userId: friendshipData.userId,
    friendId: friendshipData.friendId,
    status: friendshipData.status || 'pending',
  };

  const [insertedFriendship] = await db('userFriendships').insert(friendshipToInsert).returning('*');
  
  return mapUserFriendshipToApplicationData(insertedFriendship);
};

/**
 * Retrieves all friendships for a specific user with optional status filtering
 * 
 * @function getUserFriendships
 * @param {number} userId - User ID to get friendships for
 * @param {'pending' | 'accepted' | 'blocked'} [status] - Optional status filter
 * @param {boolean} [includeFriendInfo=false] - Whether to include friend profile info
 * @returns {Promise<UserFriendshipApplicationData[]>} Array of user's friendships
 * 
 * @description Retrieves bidirectional friendships (both initiated by user and
 * received by user) with proper performance optimization using database indexes.
 * Optionally enriches results with friend profile information.
 * 
 * @performance_optimizations
 * - Uses composite indexes (userId, status) and (friendId, status)
 * - Single query for bidirectional relationships
 * - Optional JOIN for friend info only when requested
 * 
 * @example
 * ```typescript
 * // Get all accepted friends with profile info
 * const friends = await getUserFriendships(1, 'accepted', true);
 * 
 * // Get pending requests only
 * const pending = await getUserFriendships(1, 'pending');
 * ```
 */
export const getUserFriendships = async (
  userId: number, 
  status?: 'pending' | 'accepted' | 'blocked',
  includeFriendInfo: boolean = false
): Promise<UserFriendshipApplicationData[]> => {
  let query = db('userFriendships');

  if (includeFriendInfo) {
    // Join with users table to get friend information
    query = query
      .leftJoin('users', function() {
        this.on('users.id', '=', db.raw('CASE WHEN userFriendships.userId = ? THEN userFriendships.friendId ELSE userFriendships.userId END', [userId]));
      })
      .select(
        'userFriendships.*',
        'users.email as friendEmail',
        'users.firstName as friendFirstName', 
        'users.lastName as friendLastName'
      );
  } else {
    query = query.select('userFriendships.*');
  }

  // Bidirectional friendship query - get both initiated and received
  query = query.where(function() {
    this.where('userFriendships.userId', userId).orWhere('userFriendships.friendId', userId);
  });

  if (status) {
    query = query.where('userFriendships.status', status);
  }

  const friendships = await query;

  return friendships.map((friendship: any) => {
    const friendInfo = includeFriendInfo && friendship.friendEmail ? {
      email: friendship.friendEmail,
      firstName: friendship.friendFirstName,
      lastName: friendship.friendLastName,
    } : undefined;

    return mapUserFriendshipToApplicationData(friendship, friendInfo);
  });
};

/**
 * Updates the status of an existing friendship
 * 
 * @function updateFriendshipStatus
 * @param {number} friendshipId - Friendship record ID to update
 * @param {'pending' | 'accepted' | 'blocked'} newStatus - New status to set
 * @param {number} [userId] - Optional user ID for permission validation
 * @returns {Promise<UserFriendshipApplicationData | null>} Updated friendship or null
 * 
 * @description Updates friendship status (e.g., accepting a pending request,
 * blocking a friend) with proper validation and timestamp updates.
 * 
 * @security Optional userId parameter ensures only involved users can modify
 * 
 * @example
 * ```typescript
 * // Accept a friend request
 * const accepted = await updateFriendshipStatus(1, 'accepted', 2);
 * 
 * // Block a user
 * const blocked = await updateFriendshipStatus(1, 'blocked');
 * ```
 */
export const updateFriendshipStatus = async (
  friendshipId: number,
  newStatus: 'pending' | 'accepted' | 'blocked',
  userId?: number
): Promise<UserFriendshipApplicationData | null> => {
  let query = db('userFriendships').where({ id: friendshipId });

  // Optional permission validation
  if (userId) {
    query = query.where(function() {
      this.where('userId', userId).orWhere('friendId', userId);
    });
  }

  const [updatedFriendship] = await query
    .update({ 
      status: newStatus, 
      updatedAt: new Date().toISOString() 
    })
    .returning('*');

  if (!updatedFriendship) {
    return null;
  }

  return mapUserFriendshipToApplicationData(updatedFriendship);
};

/**
 * Removes a friendship relationship between two users
 * 
 * @function deleteFriendship
 * @param {number} userId - First user ID
 * @param {number} friendId - Second user ID
 * @returns {Promise<boolean>} True if friendship was deleted, false if not found
 * 
 * @description Removes friendship record regardless of who initiated it.
 * Handles bidirectional relationship deletion properly.
 * 
 * @example
 * ```typescript
 * const deleted = await deleteFriendship(1, 2);
 * if (deleted) {
 *   console.log('Friendship removed successfully');
 * }
 * ```
 */
export const deleteFriendship = async (userId: number, friendId: number): Promise<boolean> => {
  const deletedCount = await db('userFriendships')
    .where(function() {
      this.where({ userId, friendId }).orWhere({ userId: friendId, friendId: userId });
    })
    .del();

  return deletedCount > 0;
};

/**
 * Gets a specific friendship between two users
 * 
 * @function getFriendshipBetweenUsers
 * @param {number} userId1 - First user ID
 * @param {number} userId2 - Second user ID
 * @returns {Promise<UserFriendshipApplicationData | null>} Friendship record or null
 * 
 * @description Retrieves existing friendship between two users regardless
 * of who initiated it. Useful for checking friendship status before operations.
 * 
 * @performance Uses unique constraint index for efficient lookup
 * 
 * @example
 * ```typescript
 * const friendship = await getFriendshipBetweenUsers(1, 2);
 * if (friendship?.status === 'accepted') {
 *   console.log('Users are friends');
 * }
 * ```
 */
export const getFriendshipBetweenUsers = async (
  userId1: number, 
  userId2: number
): Promise<UserFriendshipApplicationData | null> => {
  const friendship: UserFriendshipSchema | undefined = await db('userFriendships')
    .where(function() {
      this.where({ userId: userId1, friendId: userId2 })
          .orWhere({ userId: userId2, friendId: userId1 });
    })
    .first();

  if (!friendship) {
    return null;
  }

  return mapUserFriendshipToApplicationData(friendship);
};

/**
 * Gets count of friendships by status for a user
 * 
 * @function getFriendshipCounts
 * @param {number} userId - User ID to get counts for
 * @returns {Promise<{pending: number, accepted: number, blocked: number}>} Status counts
 * 
 * @description Provides efficient statistics for user's friendship status
 * distribution. Useful for dashboard displays and social features.
 * 
 * @performance Single query with GROUP BY leveraging status index
 * 
 * @example
 * ```typescript
 * const counts = await getFriendshipCounts(1);
 * console.log(`User has ${counts.accepted} friends, ${counts.pending} pending`);
 * ```
 */
export const getFriendshipCounts = async (userId: number): Promise<{
  pending: number;
  accepted: number; 
  blocked: number;
}> => {
  const result = await db('userFriendships')
    .select('status')
    .count('* as count')
    .where(function() {
      this.where('userId', userId).orWhere('friendId', userId);
    })
    .groupBy('status') as { status: string; count: number | string }[];

  const counts = { pending: 0, accepted: 0, blocked: 0 };
  
  result.forEach(row => {
    const status = row.status as keyof typeof counts;
    counts[status] = Number(row.count);
  });

  return counts;
};

/**
 * Default export object containing all UserFriendship model methods
 * 
 * @description Provides a centralized export following the established
 * pattern used by other models in the project for consistent imports.
 */
const UserFriendshipModel = {
  // Objection.js Model class
  UserFriendship,
  
  // Core CRUD operations
  createFriendship,
  getUserFriendships,
  updateFriendshipStatus,
  deleteFriendship,
  getFriendshipBetweenUsers,
  getFriendshipCounts,
  
  // Objection.js query access
  query: () => UserFriendship.query()
};

export default UserFriendshipModel;
