/**
 * @file Defines the core types used in the AI Assessment and Grading Engine.
 */

/**
 * Represents the feedback generated by the AI for a single response or an entire exercise.
 */
export interface PersonalizedFeedback {
  message: string;
  tone: 'encouraging' | 'neutral' | 'needs-improvement' | 'congratulatory' | 'motivational';
  suggestions: string[];
  motivationalQuote?: string;
  grammarTip?: string;
  culturalNote?: string;
}

/**
 * Represents the result of assessing a single user response.
 */
export interface AssessmentResult {
  assessmentTypeId?: number; // Foreign key to assessmentTypes table
  userResponse: string;
  isCorrect: boolean;
  score: number; // A score from 0 to 100
  feedback: PersonalizedFeedback;
  confidence: 'low' | 'medium' | 'high';
  metadata?: Record<string, any>;
}

/**
 * Represents the input from a user for a single question in an exercise.
 */
export interface UserResponse {
  answer: string;
  expected: string;
  type: string; // Corresponds to an assessment type name
  questionContext: string;
  category?: string;
}

/**
 * Provides the context for the entire exercise being graded.
 */
export interface ExerciseContext {
  exerciseId: number;
  learningContext: string;
  timeSpent: number; // in seconds
}

/**
 * Represents the final, aggregated result of grading an entire exercise.
 */
export interface GradingResult {
  overallScore: number;
  individualGrades: AssessmentResult[];
  categoryBreakdown: Record<string, number>; // e.g., { "Grammar": 85, "Vocabulary": 92 }
  feedback: PersonalizedFeedback;
  timeSpent: number;
  completedAt: Date;
  strengths: string[];
  weaknesses: string[];
  nextRecommendations: string[];
}
