# Content Generation API Endpoints
# Base Path: /api/ai

openapi: 3.0.0
info:
  title: AI Content Generation API
  version: 1.0.0
  description: API for generating dynamic learning content asynchronously.

paths:
  /generate:
    post:
      summary: Asynchronously generate lesson content
      description: Creates a new content generation job and returns the job ID. The client can then poll the status endpoint to get the result.
      tags:
        - Content Generation
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum: [lesson, vocabulary_drill, grammar_exercise, cultural_content, personalized_exercise]
                  description: The type of content to generate.
                level:
                  type: string
                  enum: [A1, A2, B1, B2, C1, C2]
                  description: The user's proficiency level.
                topics:
                  type: array
                  items:
                    type: string
                  description: A list of topics to focus on.
                duration:
                  type: integer
                  description: Requested content duration in minutes (e.g., 5, 10).
                focusAreas:
                  type: array
                  items:
                    type: string
                  description: Specific areas for the AI to focus on.
                learningStyle:
                  type: string
                  enum: [visual, auditory, kinesthetic, mixed]
                  description: Preferred learning style.
      responses:
        '202':
          description: Job accepted for processing.
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobId:
                    type: string
                    format: uuid
                    description: The ID of the created generation job.
        '400':
          description: Bad request due to invalid input.
        '401':
          description: Unauthorized.

  /generate/status/{jobId}:
    get:
      summary: Check the status of a content generation job
      description: Retrieves the status and, if completed, the result of a content generation job.
      tags:
        - Content Generation
      security:
        - bearerAuth: []
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Job status retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobId:
                    type: string
                  status:
                    type: string
                    enum: [pending, in-progress, completed, failed, cancelled]
                  result:
                    type: object
                    description: The generated content (present if status is 'completed').
                  error:
                    type: string
                    description: Error message (present if status is 'failed').
        '404':
          description: Job not found.

  /jobs:
    get:
      summary: List all content generation jobs for the user
      description: Retrieves a paginated list of the authenticated user's content generation jobs.
      tags:
        - Job Management
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: A list of jobs.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    status:
                      type: string
                    job_type:
                      type: string
                    created_at:
                      type: string
                      format: date-time

  /jobs/{jobId}:
    delete:
      summary: Cancel a content generation job
      description: Marks a pending or in-progress job as 'cancelled'.
      tags:
        - Job Management
      security:
        - bearerAuth: []
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Job cancelled successfully.
        '404':
          description: Job not found or cannot be cancelled.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
